# The interface for this repository (REPOSITORY_STANDARDS.md section 4): CI,
# contributors and agents all go through these targets, so a step that only
# exists in someone's shell history does not exist.
#
# Every script and gate is discovered from the tree, so a gate added today runs
# today rather than when someone remembers to list it.
SHELL := /bin/bash

ROOT := $(CURDIR)
SB := $(ROOT)/scripts/sb

# Every shell script in the repo (sorted for stable output).
SCRIPTS := scripts/sb scripts/docker-gui.sh $(sort $(wildcard scripts/test_*.sh))
# Shell gates; `test` runs them all.
TESTS := $(sort $(wildcard scripts/test_*.sh))
# Python gates (scripts/sbconfig.py and friends), run the same way.
PYTESTS := $(sort $(wildcard scripts/test_*.py))
# Generated by a gate run or a docker-gui session; `clean` removes only these.
GENERATED := scripts/__pycache__ .scratch/shadercache
DOCKER_IMAGE ?= 7dtd-safehouse:latest
DOCKER_FETCH_IMAGE ?= 7dtd-safehouse:fetch
# A Docker local volume bound to this repo's base/, not a plain `-v host:path`
# bind mount. steamcmd fails on the latter with "Failed to install app ...
# (Missing configuration)" and succeeds through the former (measured on this
# host: same image, same user, same command, only the mount mechanism differs).
# Bound to base/ so the depot lands where sb create reflinks from, with no
# 17 GB copy afterwards.
BASE_VOLUME ?= 7dtd-base

.DEFAULT_GOAL := help
.PHONY: help check lint test coverage clean version doctor docker docker-fetch
.PHONY: fetch-base-docker fetch-server-base-docker base-volume
.PHONY: fetch-base fetch-server-base create create-server up stage render-config
.PHONY: launch launch-server run stop wipe destroy list env

help:
	@echo "Safehouse: isolated, Steam-free 7DTD client and dedicated instances."
	@echo
	@echo "  make check    full static verdict (bash -n + shellcheck + py compile)"
	@echo "  make test     check + every scripts/test_*.{sh,py}; no game needed"
	@echo "  make coverage not available here (see the target for why)"
	@echo "  make clean    remove generated output only"
	@echo "  make version  the shipped version (SB_VERSION in scripts/sb)"
	@echo "  make docker   build the runtime image (client + GPU/X11, no steamcmd)"
	@echo "  make docker-fetch  build the provisioning image (steamcmd only)"
	@echo "  make fetch-server-base-docker   pull the dedicated base into ./base"
	@echo "  make fetch-base-docker          pull the client base (STEAMCMD_USER, interactive)"
	@echo "  make doctor   sb doctor (base / Proton / reflink readiness)"
	@echo
	@echo "  sb help       the full instance CLI"

# The whole static verdict. There is no separate format or type check: this
# repository is bash plus stdlib Python, and shellcheck is the analyzer.
check: lint

lint:
	bash -n $(SCRIPTS)
	@if command -v shellcheck >/dev/null 2>&1; then \
		shellcheck $(SCRIPTS); \
	elif [ -n "$${CI:-}" ]; then \
		echo "ERROR: CI requires shellcheck; e.g. pacman -S shellcheck" >&2; \
		exit 1; \
	else \
		echo "note: shellcheck not installed; skipped shell linting"; \
	fi
	python3 -m compileall -q $(PYTESTS) scripts/sbconfig.py

test: check
	set -e; for t in $(TESTS); do echo "== $$t"; bash $$t; done
	set -e; for t in $(PYTESTS); do echo "== $$t"; python3 $$t; done

# Deliberately absent rather than faked. Line coverage of `sb` needs kcov, and
# a badge this repository's CI does not regenerate is worse than no badge
# (REPOSITORY_STANDARDS.md section 2). Add kcov here and the badge to the
# README in the same change, never one without the other.
coverage:
	@echo 'no coverage target: sb is bash and would need kcov, which CI does not run.'
	@echo 'Do not add a coverage badge to the README until this target produces one.'

clean:
	rm -rf $(GENERATED)
	@echo "removed generated output; bases and instances are untouched"

version:
	@$(SB) version

# Two images, because provisioning and running need different things. The
# runtime carries no steamcmd: "no Steam at runtime" is the product claim, and
# an image shipping a Steam toolchain it never invokes contradicts it while
# carrying the supply chain anyway.
docker:
	docker build --target runtime -t $(DOCKER_IMAGE) -f Dockerfile.safehouse .

docker-fetch:
	docker build --target fetch -t $(DOCKER_FETCH_IMAGE) -f Dockerfile.safehouse .

# Fetch a base through the container, so the host needs no steamcmd.
#
# Credentials are never build inputs: a build arg or ENV lands in a layer and
# `docker history` prints it back. The client depot needs a Steam account, so
# that fetch is interactive (-it): steamcmd prompts for the password and the
# Steam Guard code, and neither is ever passed on a command line, where the
# process table would expose it. Only the account name crosses, through the
# environment.
# Recreated each time so the binding always points at this checkout's base/.
base-volume:
	@mkdir -p "$(ROOT)/base"
	@docker volume rm -f $(BASE_VOLUME) >/dev/null 2>&1 || true
	@docker volume create --driver local \
		--opt type=none --opt device="$(ROOT)/base" --opt o=bind \
		$(BASE_VOLUME) >/dev/null

# steamcmd runs as root in the container, so the depot it writes into base/ is
# chowned back to the invoking user: a root-owned base/ is one its owner can
# neither wipe nor re-fetch.
CHOWN_BASE = docker run --rm -v $(BASE_VOLUME):/sandbox/base \
	--entrypoint chown $(DOCKER_FETCH_IMAGE) -R "$$(id -u):$$(id -g)" /sandbox/base

fetch-server-base-docker: docker-fetch base-volume
	docker run --rm -v $(BASE_VOLUME):/sandbox/base $(DOCKER_FETCH_IMAGE) fetch-server-base
	$(CHOWN_BASE)

fetch-base-docker: docker-fetch base-volume
	@test -n "$${STEAMCMD_USER:-}" || { \
		echo "export STEAMCMD_USER first: app 251570 needs a Steam account that owns the game" >&2; \
		echo "leave STEAMCMD_PASS unset and type the password at the prompt" >&2; \
		exit 2; }
	docker run --rm -it -e STEAMCMD_USER -v $(BASE_VOLUME):/sandbox/base \
		$(DOCKER_FETCH_IMAGE) fetch-base
	$(CHOWN_BASE)

# --- passthrough conveniences (full CLI: scripts/sb help) ------------------

doctor:
	@$(SB) doctor

fetch-base:
	@$(SB) fetch-base

fetch-server-base:
	@$(SB) fetch-server-base

create:
	@test -n "$(NAME)" || { echo "usage: make create NAME=<instance>"; exit 2; }
	@$(SB) create $(NAME)

create-server:
	@test -n "$(NAME)" || { echo "usage: make create-server NAME=<server>"; exit 2; }
	@$(SB) create-server $(NAME)

up:
	@test -n "$(NAME)" || { echo "usage: make up NAME=<server> [TIMEOUT=240]"; exit 2; }
	@$(SB) up $(NAME) $(if $(TIMEOUT),--timeout $(TIMEOUT),)

stage:
	@test -n "$(NAME)" -a -n "$(MODS)" || { echo "usage: make stage NAME=<instance> MODS='<dir> [dir...]'"; exit 2; }
	@$(SB) stage $(NAME) $(MODS)

render-config:
	@test -n "$(NAME)" -a -n "$(PROPS)" || { echo "usage: make render-config NAME=<server> PROPS='KEY=VALUE [KEY=VALUE...]'"; exit 2; }
	@$(SB) render-config $(NAME) $(PROPS)

run:
	@test -n "$(NAME)" || { echo "usage: make run MODE=<client|server|both> NAME=<instance> [ARGS='-- -connect=...']"; exit 2; }
	@$(SB) run $(if $(MODE),$(MODE),client) $(NAME) $(ARGS)

launch:
	@test -n "$(NAME)" || { echo "usage: make launch NAME=<instance> [ARGS='-- -connect=...']"; exit 2; }
	@$(SB) launch $(NAME) $(ARGS)

launch-server:
	@test -n "$(NAME)" || { echo "usage: make launch-server NAME=<server>"; exit 2; }
	@$(SB) launch-server $(NAME)

stop:
	@test -n "$(NAME)" || { echo "usage: make stop NAME=<instance>"; exit 2; }
	@$(SB) stop $(NAME)

wipe:
	@test -n "$(NAME)" || { echo "usage: make wipe NAME=<instance>"; exit 2; }
	@$(SB) wipe $(NAME)

destroy:
	@test -n "$(NAME)" || { echo "usage: make destroy NAME=<instance>"; exit 2; }
	@$(SB) destroy $(NAME)

list:
	@$(SB) list

env:
	@test -n "$(NAME)" || { echo "usage: make env NAME=<instance>"; exit 2; }
	@$(SB) env $(NAME)
